name: corpachat

services:
  database:
    image: mysql:8.4
    restart: always
    env_file: ./user-services/.env
    ports:
      - 3306:3306
    volumes:
      - corpa-db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ambatusing
      RABBITMQ_DEFAULT_PASS: ambatubash

  api-service:
    restart: always
    env_file: ./user-services/.env
    ports:
      - 3000:${APP_PORT:-3000}
    build:
      context: user-services
      args:
        - NODE_ENV=development
        - APP_PORT=3000
    depends_on:
      - database
      - rabbitmq

  chat-service:
    restart: always
    env_file: ./chatting-services/.env
    ports:
      - 3001:${CHAT_APP_PORT:-3001}
    build:
        context: chatting-services
        args:
            - NODE_ENV=development
            - APP_PORT=3001
    depends_on:
        - rabbitmq

volumes:
  corpa-db:
