###

POST http://localhost:3000/messages/groupId1
Content-Type: application/json

{
  "senderId": "user222",
  "text": "Bangkonggggg"
}

### get all messages from group

GET http://localhost:3000/messages/groupId1

### get all data

GET http://localhost:3000/messages